services:
  # Servicio 0: Servidor de MLflow
  # Ahora solo sirve para visualizar los resultados en el navegador
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_HTTP_WHITELIST=*
    # CAMBIO: Quitamos sqlite y le decimos que lea la misma carpeta que 'train'
    command: mlflow server --backend-store-uri file:///app/mlruns --default-artifact-root file:///app/mlruns --host 0.0.0.0 --port 5000

  # Servicio 1: Entrenamiento
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      # CAMBIO: Usamos el sistema de archivos, no la red
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    depends_on:
      - mlflow

  # Servicio 2: API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./data:/app/data
    environment:
      # CAMBIO: Usamos el sistema de archivos
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    depends_on:
      train:
        condition: service_completed_successfully
      mlflow:
        condition: service_started

  monitor:
      build:
        context: .
        dockerfile: Dockerfile.monitor
      volumes:
        - ./data:/app/data
        - ./src:/app/src
        - ./models:/app/models
        - ./mlruns:/app/mlruns  # <-- Asegúrate de tener también este volumen mapeado
      environment:
        - MLFLOW_TRACKING_URI=file:///app/mlruns  # <-- NUEVO: Obliga a MLflow a ser local desde el inicio
        - PYTHONUNBUFFERED=1
      depends_on:
        - api