FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir evidently==0.4.32 watchdog

COPY backend/src/ ./src/

# Comando de arranque garantizando la carpeta de datos
CMD ["sh", "-c", "mkdir -p data && chmod 777 data && python src/monitor.py"]